### ISSUE TITLE
Problemas de descarga de munipios con guiones. ej Vila-real

### ISSUE THREAD

**Issue by sigdeletras** [sigdeletras/Spanish_Inspire_Catastral_Downloader#10]
Bug detectado por Mikel García Vaquero 
"...El bug consiste en que no se pueden descargar los datos de los municipios que contienen en su nombre un guión. Me di cuenta intentando descargar Riba-roja de Túria (RIBA-ROJA DE TURIA en el plugin) y al ver que el fallo sólo se daba allí, pasé a intentar Vila-real (VILA-REAL) y Mont-ras (MONT-RAS), con igual resultado: HTTP error 404: not found."

**Comment by FernandoM2M** [comment]
También pasa con aquellos municipios que tienen dos guiones: Lozoyuela-Navas-Sieteiglesias
![captura](https://user-images.githubusercontent.com/41516896/46197654-b810d400-c30a-11e8-93f0-3bdfcba6b26c.PNG)

**Comment by promerodiaz** [comment]
Hola, parece que el problema sigue estando. ¿Habéis encontrado alguna manera de arreglarlo?

**Comment by FernandoM2M** [comment]
Eliminando el guión del archivo de configuración "listamuni.py"

**Comment by manubenitomoreno** [comment]
Hola, gracias por éste fantástico Plug-in. Éste issue sigue activo y parece que la última PR puede solucionarlo.

**Comment by sigdeletras** [comment]
Hola a todos
Primero disculpad la gran tardanza en la respuesta. La verdad es que "abandoné" la revisión de issues y el desarrollo del complemento y dejado totalmente desatendido las mejoras del complemento.

Voy a ver si saco un rato y reviso los PR con sus correspondientes issues para añadir los municipios que dan problemas.

Gracias a todos por la colaboración y la paciencia.

**Comment by manubenitomoreno** [comment]
Hola a todos. Volví a utilizar éste código hace poco, y mi workaround fue construir las url para el request modificando el "-" por los caracteres "%20", análogamente a la url a la que se llega desde el xml. Supongo que en el plugin se podría modificar la lista de municipios, y ya estaría
Espero que os sea útil

**Comment by sigdeletras** [comment]
Hola

Después de una larga espera comentar que ha sido lazanda la v.2.0 del complemento con los siguientes cambios:

12.10.2023 V2.0:
- El complemento ya es solo compatible con versiones 3.* de QGIS
- Integrado PR de [Laura García de Marina](https://github.com/lgarciademarina) para integrar los listados de provincias y municipios desde los servicios API de Catastro
- Se separa los pasos de descarga y añadir capas al proyecto
- Añadidos más mensajes de aviso al usuario
- No es necesario convertir a geojson los GML. Se cargan los GML directamente.
- Revisiones y mejoras en el estilo de código.
- Traducción completa a inglés y español.

Un saludo
