### ISSUE TITLE
Incorporar datos del Euskadi

### ISSUE THREAD

**Issue by ccamara** [sigdeletras/Spanish_Inspire_Catastral_Downloader#11]
Hola, acabo de darme cuenta que Catastro no tiene datos de Euskadi. ¿Sería posible incorporar los datos de Euskadi a este plugin o crear uno nuevo con esta misma base que sirva para ese fin?

**Comment by sigdeletras** [comment]
Saludos @ccamara. 
Creo que en catastro de Euskadi y Navarra con gestionadas por las mismas autonomías. Desconozco si se ofrece en formato Atom según Inspire. Tampoco tenía pensado añadir más código.

Si hay algun@ interesad@ en desarrollarlo siempre podría adaptar el código. En código está bajo licencia que lo permite.
