### ISSUE TITLE
Problema con la proyección en la descarga de parcelas

### ISSUE THREAD

**Issue by PinEipolColada** [sigdeletras/Spanish_Inspire_Catastral_Downloader#12]
Buenos días,

Llevo un tiempo con un problema al descargar las parcelas catastrales. Lo he intentado desde varios PCs y el problema continúa. A pesar de tener los polígonos la proyección correcta, QGIS los dibuja en otra parte.
Adjunto capturas de pantalla de ejemplo.

Tengo una capa de municipios de España y quiero cargar las parcelas catastrales para uno de ellos. Esta capa se encuentra en ETRS89 4258
![image](https://user-images.githubusercontent.com/38682147/51172806-532abb00-18b4-11e9-990c-6730509a91e1.png)

Quiero descargar las parcelas catastrales para el municipio Santa Comba en A Coruña
![image](https://user-images.githubusercontent.com/38682147/51172930-a69d0900-18b4-11e9-8cb9-093749a45480.png)

La descarga se realiza correctamente, pero ya no se carga al espacio de trabajo
![image](https://user-images.githubusercontent.com/38682147/51173023-d9470180-18b4-11e9-9b7d-c394062c237f.png)

Y al intentar cargar la capa de forma manual, no aparece en su lugar
![image](https://user-images.githubusercontent.com/38682147/51173083-f976c080-18b4-11e9-9d56-f58ce3867e30.png)

![image](https://user-images.githubusercontent.com/38682147/51173173-2034f700-18b5-11e9-934e-4e4896fa83c2.png)
![image](https://user-images.githubusercontent.com/38682147/51173193-2f1ba980-18b5-11e9-8dd0-52b4bb3d7495.png)

¿Sabéis qué puede estar sucediendo? Me pasa desde octubre de 2018, antes nunca había tenido este problema.

Gracias por la ayuda

**Comment by sigdeletras** [comment]
Saludos

Creo que este tema es más un problema de sistema de referencia que del complemento (que los tiene).  Creo que estás cargando el SRC de catastro incorrecto. Según los metadatos los GML de Catastro están en ETRS89, pero proyectados (UMT zona 30), o lo que es lo mismo probaría a añadirlos en EPSG:25830.

De esta forma, y ya que tienes activada la proyección al vuelo, la capa de parcelas se reproyectaría a EPSG:4258 que es el SRC del proyecto y de la capa de límites y pr lo tanto iría a su lugar.

En resumen, creo que estas forzando la proyección de la capa de proyecto, cuando QGIS lo puede hacer de forma automática.

Espero que la cosa vaya por ahí.
