### ISSUE TITLE
Problema con la proyección en la descarga de parcelas (Parte 2)

### ISSUE THREAD

**Issue by CibelesR** [sigdeletras/Spanish_Inspire_Catastral_Downloader#14]
Se ha cerrado el tema sin permitir contestar.
No, no estoy forzando a ningún sistema de coordenadas del proyecto puesto que no está definido. El propio QGIS pone por defecto el que considera al descargar las capas.
Por otra parte no ha habido respuesta a que no se cargen las parcelas a pesar de selecionarlo.
En los municipios que están entre el uso 29 y 30 o 30 y 31 ya es absolutamente imposible convencerlos.

**Comment by sigdeletras** [comment]
Saludos @PinEipolColada 

En principio disculpa por el cierre del issue. Creí que con la respuesta, y ya que es un tema más de QGIS que del complemento, se había cerrado.  Si lo necesitas puedes realiziar consultas sobre QGIS en alguna de las listas ([https://lists.osgeo.org/mailman/listinfo/qgis-user](https://lists.osgeo.org/mailman/listinfo/qgis-user)) que existen o en [https://gis.stackexchange.com/?tags=qgis](https://gis.stackexchange.com/?tags=qgis)

Como te comenté estoy detectando ciertos problemas ya que parece que Catastro está suministrando de forma diferente los datos de Atom y por eso el complemento, aunque los descarga no encuentra los gml a convertir.  

Mi propuesta es que directamente descargues los archivos del servicio Atom y trabajes con ellos.
La dirección, como seguramente sabes, es  [http://www.catastro.minhap.es/webinspire/index.html](http://www.catastro.minhap.es/webinspire/index.htm) Una vez descargados ya es cuestión de trabajar con ellos con QGIS y gestionar los SRC.

También me gustaría comentar,  que este complemento es un proyecto personal y de aporte para la comunidad, con sus limitaciones y dependencias.  No existe un mantenimiento, ni una atención al cliente que obligue a responder, exclusivamente la buena disposición de ayudar y solucionar los problemas que surjan. Es importante que las consultas, dudas y aportes sigan esta misma filosofía.

Un saludo

**Comment by ferranferrer** [comment]
Hola, Patricio
Primero muchas gracias por tu aporte.
Observo que la transformación desde gml a geojson no es correcta cuándo el original de los datos epsg no es el 25830, tal cómo aparece en el gml.
Si cargas el gml directamente en qgis lo situa correctamente pero si usas el geojson lo sitúa mal (Ciutadella aparece por Cuenca -no sé para dónde mira-). Si transformas el gml a geosjon usand exportar de Qgis pasa lo mismo, parece ser que cómo la definición de geojson es con epsg 4326 ogr2ogr 'pasa' de leer el sistema original .
En la conversión se puede añadir -s_srs EPSG: (gml) leida del gml?

gracias por tu atención.
Ferran

**Comment by sigdeletras** [comment]
Hola Ferran
Tengo un poco abandona el complemento la verdad y no sé si hay opciones que han podido cambiar en la descarga de Catastro Inspire. Tendría que mirar si puedo obtener el SRC del gml y meterla como variable en la transformación.
Es cuestión de tiempo y ahora la verdad es que tengo poco.
Gracias por el aporte

**Comment by sigdeletras** [comment]
Después de una larga espera comentar que ha sido lazanda la v.2.0 del complemento con los siguientes cambios:
12.10.2023 V2.0:
- El complemento ya es solo compatible con versiones 3.* de QGIS
- Integrado PR de [Laura García de Marina](https://github.com/lgarciademarina) para integrar los listados de provincias y municipios desde los servicios API de Catastro
- Se separa los pasos de descarga y añadir capas al proyecto
- Añadidos más mensajes de aviso al usuario
- No es necesario convertir a geojson los GML. Se cargan los GML directamente.
- Revisiones y mejoras en el estilo de código.
- Traducción completa a inglés y español.
