### ISSUE TITLE
Datos faltantes de la descarga

### ISSUE THREAD

**Issue by mudomau** [sigdeletras/Spanish_Inspire_Catastral_Downloader#15]
Parece que no todos los edificios que están identificados en catastro se están descargando.

Poligono 90, Parcela 1, Toledo, Toledo - (https://www1.sedecatastro.gob.es/CYCBienInmueble/OVCConCiud.aspx?del=45&mun=900&UrbRus=R&RefC=45900A090000010000XA&Apenom=&esBice=&RCBice1=&RCBice2=&DenoBice=&from=nuevoVisor) contiene una edificación que no aparece en ninguna de las capas de edificios descargadas.

**Comment by sigdeletras** [comment]
Hola

Este aspecto depende de Catastro y es ajeno al complemento.

Un saludo
