### ISSUE TITLE
Plugin falla con Aldeaencabo de escalona

### ISSUE THREAD

**Issue by DeMadridSur** [sigdeletras/Spanish_Inspire_Catastral_Downloader#20]
Cuando intento descargar en la provincia de toledo los datos de Aldeaencabo de Escalona lo encuentro en el desplegable como 45008 - Aldeaencabo (sin de escalona). No sé si es por esto pero al descargarlo el plugin arroja un error Failed HTTP Error: 404 Not Found.

No sé cual es la URL de descargas, sería posible revisar el fichero donde se definen los municipios para subsanarlo?

Muchas gracias por adelantado,

Un Saludo y buen trabajo!

**Comment by sigdeletras** [comment]
Hola

Después de una larga espera comentar que ha sido lazanda la v.2.0 del complemento que usa directamente los servicios de Catastro para obtener los listados de provincias y municipios por lo que ya no se usa el archivo estático y este aspecto quedaría solucionado.

12.10.2023 V2.0:
- El complemento ya es solo compatible con versiones 3.* de QGIS
- Integrado PR de [Laura García de Marina](https://github.com/lgarciademarina) para integrar los listados de provincias y municipios desde los servicios API de Catastro
- Se separa los pasos de descarga y añadir capas al proyecto
- Añadidos más mensajes de aviso al usuario
- No es necesario convertir a geojson los GML. Se cargan los GML directamente.
- Revisiones y mejoras en el estilo de código.
- Traducción completa a inglés y español.

Un saludo
