### ISSUE TITLE
Convertir geoJson de crs:25830 a crs:4326

### ISSUE THREAD

**Issue by aalgamis** [sigdeletras/Spanish_Inspire_Catastral_Downloader#21]
Como se pueden convertir los archivos geoJson que devuelve la extension de tener un crs = 25830 a crs = 4326?

**Comment by sigdeletras** [comment]
Hola @aalgamis 

Usa QGIS para guardar los archivos en el CRS que desees.

**Comment by alan-replace** [comment]
@sigdeletras como mi objetivo es descargarme a través de un script de Python todos los lotes de los municipios de Catalunya, no pasaría por Qgis manualmente para podes modificar el CRS. 
Se le ocurre alguna forma de hacer esto desde Python?

**Comment by sigdeletras** [comment]
Python es un buen lenguaje para realizar este proceso. Es cuestión de ponerse manos a la obra. Usaría listas y bucles que realizaran la petición al servicios y almacenaría los datos en local. Puedes también usar librerías como PROJ o Geopandas si necesitas hacer operaciones geográficas.

Existe también mucha documentación en Internet. Yo comenzaría por esto.

**Comment by alan-replace** [comment]
> Python es un buen lenguaje para realizar este proceso. Es cuestión de ponerse manos a la obra. Usaría listas y bucles que realizaran la petición al servicios y almacenaría los datos en local. Puedes también usar librerías como PROJ o Geopandas si necesitas hacer operaciones geográficas.
> 
> 
> 
> Existe también mucha documentación en Internet. Yo comenzaría por esto.

Ya he logrado descargarme todos los lotes con un script de Python!

Ahora el desafío es poder convertir estos files de EPSG:25830 a EPSG:4326.
No he logrado hacerlo mediante Geodataframes extrañamente.
Ha realizado esto anteriormente? Tiene algún tip sobre cómo hacerlo?
