### ISSUE TITLE
Incidencia de descarga con ‘Spanish Inspire Catastral Downloader’

### ISSUE THREAD

**Issue by Juanlu61** [sigdeletras/Spanish_Inspire_Catastral_Downloader#29]
Buenos días…,

Creo haber detectado un error en los datos descargados desde QGIS por la aplicación ‘Spanish Inspire Catastral Downloader’. He procedido a La descarga de los archivos correspondientes a construcciones de 11 - CADIZ, 53020 – JEREZ DE LA FRONTERA. Pero me he encontrado con que el archivo A.ES.SDGC.BU.53020.buildingpart.gml está incompleto. Su tamaño es muy inferior al que en realidad le debe corresponder, y al cargarlo y visualizarlo en QGIS no aparece en su totalidad.

Gracias.

![Sin título-1](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/assets/166791742/44d84551-f279-4923-a0cd-36c870cd6947)

**Comment by Jorge-UDC** [comment]
Buenos días, 
Me sucede lo mismo, versión actual 3.28.1 Firenze. Windows 11. La capa building part está al 10% aproximadamente. Es general, adjunto ejemplo de Madrid
![Madrid](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/assets/98218389/2a8289f6-bf2c-4782-a6ef-58394d873192)

**Comment by Jorge-UDC** [comment]
Hola, parece que ya funciona. Gracias!

**Comment by sigdeletras** [comment]
Hola Jorge,

El tema que me comentas sobre los datos de la capa de buildingpart no depende del complemento sino direcatemente de la web de Catastro.  Según lo que he podrido leer en foros,  en los buildingparts, sólo vienen features de volúmenes con plantas bajo tierra, pero ninguno para plantas sobre suelo. Han debido aplicar un filtro mal en la exportación. Igual, en la próxima publicación de los datos lo arreglen.

Un saludo.

**Comment by Jorge-UDC** [comment]
Gracias! Debe ser como dices, ya que hace una semana todavía no se descargaban completos y ayer ya funcionaba bien. Ahora va perfectamente. Muchas gracias por el plugin, que usamos constantemente! Saludos
