### ISSUE TITLE
Error classFactory()

### ISSUE THREAD

**Issue by jesbrz** [sigdeletras/Spanish_Inspire_Catastral_Downloader#5]
I get this error trying to install plugin:

No se pudo cargar el complemento 'Spanish_Inspire_Catastral_Downloader' debido a un error al llamar a su método classFactory() 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Spanish_Inspire_Catastral_Downloader/__init__.py", line 35, in classFactory
    return Spanish_Inspire_Catastral_Downloader(iface)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/Spanish_Inspire_Catastral_Downloader/Spanish_Inspire_Catastral_Downloader.py", line 85, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Versión de Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
Versión de QGIS: 3.0.3-Girona Girona, exported 

Ruta de Python:
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Volumes/xxxxxxUsers/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by sigdeletras** [comment]
Saludos,

No trabajo con Mac, lo siento. No sé a que se debe el error. Prueba la última versión (1.0) para comprobar si persiste.
