### ISSUE TITLE
En Qgis3 (Ubuntu Mac)  descarga los datos gml pero no se leen.

### ISSUE THREAD

**Issue by dieza** [sigdeletras/Spanish_Inspire_Catastral_Downloader#8]
En Qgis3 (Ubuntu Mac)  descarga los datos gml pero no se leen, ni se quedan en el TOC. El fichero gml generado si que lo lee la 2.18. He probado con l'Alqueria d'Asnar (Alacant) que es un municipio muy pequeño.
Al cargarlo tiene el icono de imagen en lugar del vectorial, a pesar de que si que parece entender que se trata de un archivo gml

Original | A.ES.SDGC.CP.39027.cadastralparcel CadastralParcel
-- | --
Name | A.ES.SDGC.CP.39027.cadastralparcel CadastralParcel
Source | /Users/agus/catastro/CatAtom2Osm/39027/A.ES.SDGC.CP.39027/A.ES.SDGC.CP.39027.cadastralparcel.gml
Storage | GML
Comment |  
Encoding | UTF-8
Geometry | Unknown geometry (GeometryCollection)
CRS | EPSG:4326 - WGS 84 - Geographic
Extent | Empty
Unit | degrees
Feature count | 10850

Original | A.ES.SDGC.CP.03017.cadastralzoning CadastralZoning
-- | --
Name | A.ES.SDGC.CP.03017.cadastralzoning CadastralZoning
Source | 03017-L ALQUERIA D ASNAR/A.ES.SDGC.CP.03017.cadastralzoning.gml
Storage | GML
Comment |  
Encoding | UTF-8
Geometry | Unknown geometry (GeometryCollection)
CRS | EPSG:4326 - WGS 84 - Geographic
Extent | Empty
Unit | degrees
Feature count | 28

------------
[03017-L ALQUERIA D ASNAR_Parcels.zip](https://github.com/sigdeletras/Spanish_Inspire_Catastral_Downloader/files/2115085/03017-L.ALQUERIA.D.ASNAR_Parcels.zip)

**Comment by sigdeletras** [comment]
Saludos @dieza ¿qué versión del complemento tienes instalada? 
Ese es el error que acabamos de arreglar en la versión 1.0.  QGIS 3 no representa bien los GML de Castastro. La solución ha sido convertirlos a geojson.

**Comment by sigdeletras** [comment]
Buenas de nuevo @dieza 
Me acaban de escribir un correo, comentando que tenían problemas con la descarga de archivos, en los que también se crea la carpeta por con espacios (ej 46172-MOIXENT   MOGENTE). 
Creo que hay revisar el comando que convierte a geojson para que no cree la carpeta con espacios y funcione.

**Comment by sigdeletras** [comment]
Solucionado con la versión 1.0
